version: '3'

services:

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - web-root:/var/www/html
      - ./config/nginx-conf:/etc/nginx/conf.d
    depends_on:
      - redis
      - mongo
      - back-end
    networks:
      - real-time-chat

  redis:
    image: redis:4.0-alpine
    restart: unless-stopped
    networks:
      - real-time-chat
    volumes:
      - redisdata:/data
    ports:
      - "6379:6379"

  mongo:
    image: mongo:3.6
    restart: unless-stopped
    networks:
      - real-time-chat
    volumes:
      - mongodata:/data/db
      - mongoconfig:/data/configdb
    ports:
      - "27017:27017"

  back-end:
    build:
      context: .
      dockerfile: docker/Dockerfile
    networks:
      - real-time-chat
    depends_on:
      - mongo
      - redis
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_HOST=redis
      - MONGO_HOST=0.0.0.0
      - MONGO_PORT=27017
      - MONGO_USER=
      - MONGO_PASS=
      - JWT_SECRET_KEY=Amgad
      - MAIL_USED_TO_SEND_EMAILS=amgadatef456@gmail.com
      - MAIL_USED_TO_SEND_EMAILS_Password=airpodsPro123
      - FRONT_END_ORIGIN=http://127.0.0.1:8000
    expose:
      - "3000"

networks:
  real-time-chat:
    driver: "bridge"

volumes:
  mongodata:
    driver: local
  mongoconfig:
    driver: local
  redisdata:
    driver: local
  web-root:
    driver: local
